### ISSUE TITLE
Greetings from Eve, I want to know how can I use it

### ISSUE THREAD

**Issue by eveyw** [XBWer/JDT_AST_DOT#1]
Hey, I want to generate AST for my own java codes input. Can I refer to your code and use it?

If applicant, what tool should I use to build this project and run it?

Thanks!

**Comment by maxxbw54** [comment]
Hi @wyang41 , pls feel free to use it. :-)

If I remember correctly, all you need to do is import the libs (Dependency stuff) to your project, then it should be work.

If not, pls let me know the issue, I will try to fix it.

**Comment by eveyw** [comment]
Hey, sry I’m not familiar with JAVA and Java compiler things. Would you mind if you provide the a little bit detailed processes to carry it out?

Thanks

**Comment by maxxbw54** [comment]
Hi @wyang41 ,

1. Install Java in your PC;
2. Download an IDE (e.g., eclipse), and import the libs to your project.
3. Run it.

You can get more details about steps from Google search.

**Comment by wyang41** [comment]
Thanks, coz I used eclipse to run this project and thought it can solve all the binding and complied things, but it showed “error coz cannot find lib path”

**Comment by eveyw** [comment]
Hi sorry to bother. I successfully compiled and ran the project, also changed the path to test.java into my own. But the result is always "Not a file". 
Even in the situation, I didn't change the path in 'main.java', which means it still points to folders in your computer, but the project still could run and have a output "not a file".

I think this is not correct, is it?

Thanks

**Comment by maxxbw54** [comment]
@wyang41 Did you modify the path setting in https://github.com/XBWer/JDT_AST_DOT/blob/master/src/main/Main.java?
